sequenceDiagram
  participant participant_clamp as clamp
  participant participant_createEntityStyle as createEntityStyle
  participant participant_GameEntity as GameEntity
  participant participant_toPercent as toPercent
  participant_GameEntity->>participant_createEntityStyle: createEntityStyle()
  participant_createEntityStyle->>participant_toPercent: toPercent()
  participant_toPercent->>participant_clamp: clamp()
  participant_clamp-->>participant_toPercent: return
  participant_toPercent-->>participant_createEntityStyle: return
  participant_createEntityStyle->>participant_clamp: clamp()
  participant_clamp-->>participant_createEntityStyle: return
  participant_createEntityStyle-->>participant_GameEntity: return
