sequenceDiagram
  participant participant_GameOverlay as GameOverlay
  participant participant_resolvePlacementStyle as resolvePlacementStyle
  participant_GameOverlay->>participant_resolvePlacementStyle: resolvePlacementStyle()
  participant_resolvePlacementStyle-->>participant_GameOverlay: return
