import type { ZoraComponentMeta } from '@ankhorage/zora/metadata';

/*** Describe one positioned generic game entity for ZORA authoring tools. */
export const gameEntityMeta = {
  name: 'GameEntity',
  category: 'component',
  description: 'Positions arbitrary visual content inside a GameField without owning game rules.',
  directManifestNode: true,
  allowedChildren: ['Badge', 'Icon', 'Image', 'Text', 'View'],
  blueprint: {
    label: 'Game entity',
    defaultProps: { x: 0, y: 0, opacity: 1, scale: 1, rotation: 0, zIndex: 0 },
  },
  bindings: {
    props: {
      x: { value: { type: 'number' }, acceptsFallback: true },
      y: { value: { type: 'number' }, acceptsFallback: true },
      width: { value: { type: 'number' }, acceptsFallback: true },
      height: { value: { type: 'number' }, acceptsFallback: true },
      opacity: { value: { type: 'number' }, acceptsFallback: true },
      scale: { value: { type: 'number' }, acceptsFallback: true },
      rotation: { value: { type: 'number' }, acceptsFallback: true },
      zIndex: { value: { type: 'number' }, acceptsFallback: true },
      hidden: { value: { type: 'boolean' }, acceptsFallback: true },
      measurementId: { value: { type: 'string' }, acceptsFallback: true },
      transitionDurationMs: { value: { type: 'number' }, acceptsFallback: true },
      transitionEasing: { value: { type: 'string' }, acceptsFallback: true },
      motionOffsetX: { value: { type: 'number' }, acceptsFallback: true },
      motionOffsetY: { value: { type: 'number' }, acceptsFallback: true },
      motionOpacityDelta: { value: { type: 'number' }, acceptsFallback: true },
      motionScaleDelta: { value: { type: 'number' }, acceptsFallback: true },
      motionRotationDelta: { value: { type: 'number' }, acceptsFallback: true },
      motionDurationMs: { value: { type: 'number' }, acceptsFallback: true },
      motionDelayMs: { value: { type: 'number' }, acceptsFallback: true },
      motionEasing: { value: { type: 'string' }, acceptsFallback: true },
      motionRepeat: { value: { type: 'boolean' }, acceptsFallback: true },
      motionAlternate: { value: { type: 'boolean' }, acceptsFallback: true },
      motionPaused: { value: { type: 'boolean' }, acceptsFallback: true },
      motionEssential: { value: { type: 'boolean' }, acceptsFallback: true },
    },
  },
  props: {
    x: {
      type: 'number',
      category: 'Position',
      label: 'X (%)',
      default: 0,
      authoring: { authority: 'instance' },
    },
    y: {
      type: 'number',
      category: 'Position',
      label: 'Y (%)',
      default: 0,
      authoring: { authority: 'instance' },
    },
    width: {
      type: 'number',
      category: 'Size',
      label: 'Width',
      authoring: { authority: 'instance' },
    },
    height: {
      type: 'number',
      category: 'Size',
      label: 'Height',
      authoring: { authority: 'instance' },
    },
    opacity: {
      type: 'number',
      category: 'Appearance',
      label: 'Opacity',
      default: 1,
      authoring: { authority: 'instance' },
    },
    scale: {
      type: 'number',
      category: 'Transform',
      label: 'Scale',
      default: 1,
      authoring: { authority: 'instance' },
    },
    rotation: {
      type: 'number',
      category: 'Transform',
      label: 'Rotation',
      default: 0,
      authoring: { authority: 'instance' },
    },
    zIndex: {
      type: 'number',
      category: 'Position',
      label: 'Z index',
      default: 0,
      authoring: { authority: 'instance' },
    },
    hidden: {
      type: 'boolean',
      category: 'State',
      label: 'Hidden',
      default: false,
      authoring: { authority: 'instance' },
    },
    pointerEvents: {
      type: 'enum',
      category: 'Interaction',
      label: 'Pointer events',
      enum: ['auto', 'box-none', 'box-only', 'none'],
      default: 'auto',
      authoring: { authority: 'instance' },
    },
    measurementId: {
      type: 'string',
      category: 'Measurement',
      label: 'Measurement id',
      authoring: { authority: 'instance' },
    },

    transitionDurationMs: {
      type: 'number',
      category: 'Motion',
      label: 'Transition duration (ms)',
      default: 0,
      authoring: { authority: 'instance' },
    },
    transitionEasing: {
      type: 'enum',
      category: 'Motion',
      label: 'Transition easing',
      enum: ['linear', 'ease-in', 'ease-out', 'ease-in-out'],
      default: 'linear',
      authoring: { authority: 'instance' },
    },
    motionOffsetX: {
      type: 'number',
      category: 'Motion',
      label: 'Motion X offset (%)',
      default: 0,
      authoring: { authority: 'instance' },
    },
    motionOffsetY: {
      type: 'number',
      category: 'Motion',
      label: 'Motion Y offset (%)',
      default: 0,
      authoring: { authority: 'instance' },
    },
    motionOpacityDelta: {
      type: 'number',
      category: 'Motion',
      label: 'Motion opacity delta',
      default: 0,
      authoring: { authority: 'instance' },
    },
    motionScaleDelta: {
      type: 'number',
      category: 'Motion',
      label: 'Motion scale delta',
      default: 0,
      authoring: { authority: 'instance' },
    },
    motionRotationDelta: {
      type: 'number',
      category: 'Motion',
      label: 'Motion rotation delta',
      default: 0,
      authoring: { authority: 'instance' },
    },
    motionDurationMs: {
      type: 'number',
      category: 'Motion',
      label: 'Motion duration (ms)',
      default: 0,
      authoring: { authority: 'instance' },
    },
    motionDelayMs: {
      type: 'number',
      category: 'Motion',
      label: 'Motion delay (ms)',
      default: 0,
      authoring: { authority: 'instance' },
    },
    motionEasing: {
      type: 'enum',
      category: 'Motion',
      label: 'Motion easing',
      enum: ['linear', 'ease-in', 'ease-out', 'ease-in-out'],
      default: 'linear',
      authoring: { authority: 'instance' },
    },
    motionRepeat: {
      type: 'boolean',
      category: 'Motion',
      label: 'Repeat motion',
      default: false,
      authoring: { authority: 'instance' },
    },
    motionAlternate: {
      type: 'boolean',
      category: 'Motion',
      label: 'Alternate motion',
      default: false,
      authoring: { authority: 'instance' },
    },
    motionPaused: {
      type: 'boolean',
      category: 'Motion',
      label: 'Pause motion',
      default: false,
      authoring: { authority: 'instance' },
    },
    motionEssential: {
      type: 'boolean',
      category: 'Motion',
      label: 'Essential motion',
      default: false,
      authoring: { authority: 'instance' },
    },
    accessibilityLabel: {
      type: 'string',
      category: 'Accessibility',
      label: 'Accessibility label',
      authoring: { authority: 'instance' },
    },
  },
} as const satisfies ZoraComponentMeta;
